### ISSUE TITLE
Is this supported with a recent version of Miniconda3?

### ISSUE THREAD

**Issue by maaren** [rinikerlab/mlddec#1]
Using Miniconda3-py37_4.9.2-Linux-x86_64.sh on Linux I get when running the example in README.md:
```
(base) [maaren mlddec]$ python tessie.py
Loading models...
  0%|                                                    | 0/10 [00:00<?, ?it/s]/home/maaren/miniconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.tree.tree module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.tree. Anything that cannot be imported from sklearn.tree is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/maaren/miniconda3/lib/python3.7/site-packages/sklearn/base.py:334: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.21.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
100%|███████████████████████████████████████████| 10/10 [00:17<00:00,  1.76s/it]
Checking through molecule dataset, stops when discrepencies are observed...
  0%|▏                                    | 164/40019 [01:06<3:59:17,  2.78it/s]No close match for ['O=c1[nH]cnc2c([C@]3(CO)NC[C@H](O)[C@@H]3O)c[nH]c12'
 'COC(=O)c1cc(OC)c2oc(=O)c(=O)[nH]c2c1'
 'COc1cc2c(cc1OC)C(=O)N1C=C(/C=C/C(N)=O)C[C@H]1C=N2' ...
 'O=[S+](O)(c1ccc(Br)cc1F)N1CCC(O)CC1'
 'C=C1C(=O)O[C@H]2C[C@@H](C)[C@@H]3C[C@@H](O)[C@H](O)[C@@]3(C)[C@H](O)[C@H]12'
 'COc1ccc2c(c1)c1c(n2C)C2(O)c3ccccc3C2CC1'], validation terminated.
  0%|▏                                    | 164/40019 [01:06<4:29:00,  2.47it/s]
/home/maaren/git/mlddec/mlddec/utils.py:101: UserWarning: Have you added hydrogens to the molecule?
  warnings.warn("Have you added hydrogens to the molecule?", UserWarning)
/home/maaren/git/mlddec/mlddec/utils.py:101: UserWarning: Have you added hydrogens to the molecule?
  warnings.warn("Have you added hydrogens to the molecule?", UserWarning)
Traceback (most recent call last):
  File "tessie.py", line 17, in <module>
    mlddec.add_charges_to_mol(mol, charges)
  File "/home/maaren/git/mlddec/mlddec/utils.py", line 154, in add_charges_to_mol
    charges = get_charges(mol, model_dict)
  File "/home/maaren/git/mlddec/mlddec/utils.py", line 127, in get_charges
    per_tree_pred = [tree.predict(arr.reshape(1,-1)) for tree in model_dict[element]]
IndexError: list index out of range
```

**Comment by greglandrum** [comment]
Hi @maaren, thanks for reporting the problem.
I'm unable to reproduce the behavior you're seeing using a python 3.7 environment built with a recent version of conda (I actually see another problem, which we'll also take a look into).
Let's start by tracking which versions of the python packages you are using... can you please run 
`conda list > packages.txt`
and attach the resulting packages.txt file to a reply here?

**Comment by maaren** [comment]
```$ cat packages.txt 
# packages in environment at /home/maaren/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
brotlipy                  0.7.0           py37h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.14.12              h8948797_3  
certifi                   2020.12.5        py37h89c1867_0    conda-forge
cffi                      1.14.3           py37h261ae71_2  
chardet                   3.0.4           py37h06a4308_1003  
conda                     4.9.2            py37h89c1867_0    conda-forge
conda-package-handling    1.7.2            py37h03888b9_0  
cryptography              3.2.1            py37h3c74f83_1  
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
glib                      2.66.1               h92f7085_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
intel-openmp              2020.2                      254  
joblib                    1.0.0              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.3.1            py37hc928c03_0    conda-forge
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libboost                  1.73.0              hf484d3e_11  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.2                heb0550a_3  
matplotlib                3.3.3            py37h89c1867_0    conda-forge
matplotlib-base           3.3.3            py37h4f6019d_0    conda-forge
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.2.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
numpy                     1.19.2           py37h54aff64_0  
numpy-base                1.19.2           py37hfa32c7d_0  
olefile                   0.46                     py37_0  
openssl                   1.1.1i               h27cfd23_0  
pandas                    1.1.5            py37ha9443f7_0  
pcre                      8.44                 he6710b0_0  
pillow                    8.0.1            py37he98fc37_0  
pip                       20.2.4           py37h06a4308_0  
pixman                    0.40.0               h7b6447c_0  
py-boost                  1.73.0          py37h04863e7_11  
pycosat                   0.6.3            py37h27cfd23_0  
pycparser                 2.20                       py_2  
pyopenssl                 19.1.0             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py37hcca6a23_4    conda-forge
pysocks                   1.7.1                    py37_1  
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1                      py_0  
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.5             pyhd3eb1b0_0  
qt                        5.9.7                h5867ecd_1  
rdkit                     2020.09.1.0      py37hd50e099_1    rdkit
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                     py_0  
ruamel_yaml               0.15.87          py37h7b6447c_1  
scikit-learn              0.23.2           py37h0573a6f_0  
scipy                     1.5.2            py37h0b6359f_0  
setuptools                50.3.1           py37h06a4308_1  
sip                       4.19.8           py37hf484d3e_0  
six                       1.15.0           py37h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tk                        8.6.10               hbc83047_0  
tornado                   6.1              py37h4abf009_0    conda-forge
tqdm                      4.55.1             pyhd8ed1ab_0    conda-forge
urllib3                   1.25.11                    py_0  
wheel                     0.35.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
```

**Comment by greglandrum** [comment]
Thanks @maaren! I don't see anything particularly odd there
Can you also share the molecule which is causing the error?

**Comment by maaren** [comment]
I just tried to run the example in the README:
```
(base) [maaren@csb mlddec]$ cat tessie.py
import mlddec


#Load all the machine-learned models for a given epsilon, currently only epsilon of 4 or 78 is available. The latter gives more polar charges
epsilon = 4
models  = mlddec.load_models(epsilon)

#If you want to validate the installation is correct, you can run the following:
mlddec.validate_models(models, epsilon)

#To charge a molecule, run the following:
from rdkit import Chem
#mol = Chem.MolFromSmiles("c")
mol = Chem.MolFromSmiles("c1ccccc1")

charges = mlddec.get_charges(mol, models)
mlddec.add_charges_to_mol(mol, charges)

#You can look at the molecule in 2D with the assigned charges with:
mlddec.visualise_charges(mol)

#Once you charged all the molecules, you should unload the models as they consume quite some memory
del models

```

**Comment by greglandrum** [comment]
This may not explain the problem that you are having, but after some experimentation I managed to figure out that the mlddec code can only be relied upon to produce reliable results for the version of the RDKit which was used to build the models (a change in the RDKit's chemistry model causes different atom-pair fingerprints to be generated and this results in different predictions from mlddec).

You probably want to create a separate conda environment for this, but then please try switching to v2019.03 of the rdkit in that environment:
```
conda install -c conda-forge rdkit=2019.03
```

While you are at it, it's probably best to also switch to an older version of sklearn just to make sure that there are no problems unpickling the saved models:
```
conda install -c conda-forge scikit-learn=0.21.1
```

If you just want to reproduce the environment I used, here's a YML file. If you remove the `.txt` from the name, you can create the matching environment on linux with:
```
conda env create -f py37_mlddec.yml
```

[py37_mlddec.yml.txt](https://github.com/rinikerlab/mlddec/files/5807355/py37_mlddec.yml.txt)

We're going to look into getting a version which works with more up-to-date versions of the RDKit and sklearn, but in the meantime this should hopefully help you get something working.

**Comment by maaren** [comment]
I am getting this now:
```
(py37_mlddec) [maaren@csb mlddec]$ python tessie2.py 
Loading models...
100%|███████████████████████████████████████████| 10/10 [00:16<00:00,  1.67s/it]
/home/maaren/git/mlddec/mlddec/utils.py:108: UserWarning: Have you added hydrogens to the molecule?
  warnings.warn("Have you added hydrogens to the molecule?", UserWarning)
/home/maaren/git/mlddec/mlddec/utils.py:108: UserWarning: Have you added hydrogens to the molecule?
  warnings.warn("Have you added hydrogens to the molecule?", UserWarning)
Traceback (most recent call last):
  File "tessie2.py", line 19, in <module>
    mlddec.add_charges_to_mol(mol, charges)
  File "/home/maaren/git/mlddec/mlddec/utils.py", line 161, in add_charges_to_mol
    charges = get_charges(mol, model_dict)
  File "/home/maaren/git/mlddec/mlddec/utils.py", line 134, in get_charges
    per_tree_pred = [tree.predict(arr.reshape(1,-1)) for tree in model_dict[element]]
IndexError: list index out of range

```

**Comment by maaren** [comment]
The example in the example directory is working, so I changed the code in the README to:
```
#charges = mlddec.get_charges(mol, models)
print("Na charges")

mlddec.add_charges_to_mol(mol, models)
#mlddec.add_charges_to_mol(mol, charges)
```
That seems to work.
